FROM maven:3.8.8-eclipse-temurin-8 AS builder
WORKDIR /app

COPY pom.xml /app
COPY src /app/src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:8-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8888

ENTRYPOINT ["java", "-jar", "app.jar"]