services:
  app:
    build:
      context: ../../
      dockerfile: ops-tools/docker/images/app/Dockerfile.prod
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/school
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: school
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - docker-practice-net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - docker-practice-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d school" ]
      interval: 10s
      retries: 5
      start_period: 10s

  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - docker-practice-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 5s

networks:
  docker-practice-net:
    driver: bridge